name: build-and-deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # 6時間おき（UTC）

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feed (Atom)
        run: python build_feed.py

      - name: Compare with live atom.xml
        id: diff
        shell: bash
        run: |
          set -e
          curl -fsSL "https://tatitle.github.io/kirapo-rss/atom.xml" -o live.xml || true
          if [ -f live.xml ] && cmp -s live.xml public/atom.xml ; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No change in atom.xml"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Atom feed changed"
          fi

      - name: Setup Pages
        if: steps.diff.outputs.changed == 'true'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.diff.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    if: needs.build.outputs.changed == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
